Draft: hook-digest: Add hook for computing digests
VILLASframework/node pull request #707
Opened 2023-08-28 13:52 UTC by PJungkamp

Resolves: #702

2023-08-28 15:10 UTC, PJungkamp commented
@stv0g I'm not quite sure how to configure the `flags` of a `Format`. E.g for the `villas.human` format.

I see that the constructor of a `Format` is passed a set of flags. See https://github.com/VILLASframework/node/blob/b9bad1219d69b0e601342ba5c81e4c712a71d286/lib/format.cpp#L60-L64
But I'm instantiating the Format using `FormatFactory::make` which does not take flags for an argument.

2023-08-29 14:44 UTC, PJungkamp commented
It's kind of unfortunate that I had to transition to older APIs to support `OpenSSL 1.1.1`. Especially since `OpenSSL 1.1.1` reaches its end of life in less than two months.

2023-08-31 08:17 UTC, stv0g requested changes
Thanks :) Looks good 👍🏻

2023-08-31 08:17 UTC, stv0g commented on doc/openapi/components/schemas/config/hooks/digest.yaml
> +    - "algorithm"
```suggestion
  required:
  - uri
  - mode
  - interval
  - algorithm
```

2023-08-31 08:17 UTC, stv0g commented on lib/hooks/digest.cpp
> +#include <fmt/format.h>
Include order

```suggestion
#include <optional>
#include <variant>
#include <string>
#include <iterator>
#include <memory>

#include <openssl/evp.h>
#include <openssl/crypto.h>
#include <fmt/format.h>

#include <villas/utils.hpp>
#include <villas/format.hpp>
#include <villas/hook.hpp>
#include <villas/sample.hpp>
#include <villas/timing.hpp>
#include <villas/exceptions.hpp>
```

2023-08-31 08:17 UTC, stv0g commented on lib/hooks/digest.cpp
> +static void FILE_free(FILE *f) {
```suggestion
static void FILE_free(FILE *f)
{
```

2023-08-31 08:17 UTC, stv0g commented on lib/hooks/digest.cpp
> +} /* namespace villas */
I am trying to refactor the codebase to use C++ style comments (`//`) rather C-style (`/* */`)

```suggestion
} // namespace node
} // namespace villas
```

2023-08-31 08:17 UTC, stv0g commented on lib/hooks/digest.cpp
> +/* Register hook */
```suggestion
// Register hook
```

2023-08-31 08:17 UTC, stv0g commented on lib/hooks/digest.cpp
> + *********************************************************************************/
Part of a cleanup which I am currently performing in another PR
```suggestion
/* Digest hook.
 *
 * Author: Philipp Jungkamp <philipp.jungkamp@opal-rt.com>
 * SPDX-FileCopyrightText: 2023 OPAL-RT Germany GmbH
 * SPDX-License-Identifier: Apache-2.0
 */
```

2023-08-31 08:17 UTC, stv0g commented on doc/openapi/components/schemas/config/hooks/_digest.yaml
> +allOf:
```suggestion
# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
# SPDX-FileCopyrightText: 2023 OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0
---
allOf:
```

2023-08-31 08:17 UTC, stv0g commented on etc/examples/hooks/digest.conf
> +@include "hook-nodes.conf"
```suggestion
# SPDX-FileCopyrightText: 2023 OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

@include "hook-nodes.conf"
```

2023-08-31 08:17 UTC, stv0g commented on lib/hooks/digest.cpp
> +	bool updateInterval(Sample *smp) {
Should be pass `const Sample *smp`?

2023-08-31 08:17 UTC, stv0g commented on lib/hooks/digest.cpp
> +	void updateDigest(Sample *smp) {
Should be pass `const Sample *smp`?

2023-09-06 06:59 UTC, stv0g commented
> Should I just use the black formatter?

2023-09-11 10:59 UTC, PJungkamp commented
> But after our discussion yesterday, we should also consider moving the timestamping code to the SEGuRo Platform repo.

I'll probably just remove the script in the `tools` directory.

2023-09-13 09:07 UTC, PJungkamp commented on lib/hooks/frame.cpp
> +      }
LLVM codestyle for switch case with scoped cases is weird.

2023-09-13 09:07 UTC, PJungkamp commented on doc/openapi/components/schemas/config/hooks/frame.yaml
> +      enum:
unit has no default.

2023-09-13 09:09 UTC, PJungkamp commented on doc/openapi/components/schemas/config/hooks/digest.yaml
> +      type: string
No, I wanted this to be explicit.

2023-09-13 12:27 UTC, stv0g commented
- [ ] Default values OpenAPI schema of framing hook
- [ ] `json_flags` vs `flags_json`
- [ ] Remove initialization `last_sample->flags`
- [ ] Integration tests for new hooks: reorder, frame, digest
- [ ] path_source proper fixups for `muxed_sample->flags`

2023-09-15 14:37 UTC, PJungkamp commented
@stv0g Could you have a look at the failing `hook-digest` integration test. I can't reproduce the error locally.

2023-09-19 14:10 UTC, stv0g approved these changes

2023-09-19 17:07 UTC, merged