Fix formatting using clang-format
VILLASframework/node pull request #722
Opened 2024-02-08 14:55 UTC by stv0g

2024-02-08 15:01 UTC, fwege approved these changes

2024-02-10 12:50 UTC, n-eiling requested changes

2024-02-10 12:50 UTC, n-eiling commented on lib/nodes/rtp.cpp
I think the order matters in this file. The CI fails because some types are unknown.

2024-02-13 13:52 UTC, stv0g commented on lib/nodes/rtp.cpp
Thanks. I've locally disabled clang-format for this section of the file.

2024-02-14 09:09 UTC, n-eiling approved these changes

2024-02-14 09:09 UTC, merged