Refactor: Device refactor to integrate Platform-Devices
VILLASframework/node pull request #814
Opened 2024-08-14 16:45 UTC by IgnoreWarnings

Rename (pci::)Device to PciDevice and move it to devices folder. Change DeviceList to PciDeviceList. Change namespace from pci to devices.
#808 Introduces a Device interface which will integrate Pci Devices and Platform Devices.

2024-08-21 08:01 UTC, n-eiling approved these changes

2024-08-29 14:56 UTC, n-eiling commented
@stv0g we are waiting for your approval :)

2024-08-30 08:13 UTC, stv0g commented
Glaube da sind irgendwie Zertifikate in der CI abgelaufen:

```
tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-08-29T15:02:11Z is after 2024-08-29T08:34:57Z
```

2024-08-30 08:18 UTC, stv0g requested changes
Looks good to me :) Could you rename `pci_device.hpp` to just `pci.hpp`, fix the CI and remove to one superfluous parantheses?

Thanks :) 👍🏻

2024-08-30 08:18 UTC, stv0g commented on common/lib/CMakeLists.txt
> +        kernel/devices/pci_device.cpp
Would it be okay, if we rename it to `kernel/devices/pci.h`? I dislike the duplication of `device` in the path.

2024-08-30 08:18 UTC, stv0g commented on fpga/lib/pcie_card.cpp
> +    (kernel::devices::Id(FPGA_PCI_VID_XILINX, FPGA_PCI_PID_VFPGA)));
Isnt there one `(` too much?

2024-08-30 10:00 UTC, n-eiling commented
I guess it was fixed. I fixed the CI by rerunning it.

2024-08-30 10:21 UTC, stv0g commented on common/lib/CMakeLists.txt
> +        kernel/devices/pci_device.cpp
Okay, good argument. Lets keep `pci_device.hpp` then

2024-08-30 10:21 UTC, stv0g commented on fpga/lib/pcie_card.cpp
> +    (kernel::devices::Id(FPGA_PCI_VID_XILINX, FPGA_PCI_PID_VFPGA)));
Could you fix it?

2024-08-30 10:22 UTC, stv0g approved these changes

2024-08-30 10:22 UTC, stv0g commented on fpga/lib/pcie_card.cpp
> +    (kernel::devices::Id(FPGA_PCI_VID_XILINX, FPGA_PCI_PID_VFPGA)));
Nevermind, I am gonna merge this now. It would be nice if it could be addresses in a subsequent MR

2024-08-30 10:23 UTC, merged