Pi5 runner
VILLASframework/node pull request #823
Opened 2024-10-22 07:41 UTC by al3xa23

Hi, 

just realized that the old PR from this branch was closed. I rebased this branch so that we can merge it.

2024-10-22 08:01 UTC, stv0g requested changes
We should include the Arm64 Docker image into the manifest here:
https://github.com/VILLASframework/node/blob/248bbf55c7228c1ab106e1efdc178d56cdc3a157/.gitlab-ci.yml#L216

It would also nice if we could stick with the convention and use lowercase tags to select the runners. `PI5` falls outside the convention here..

2024-10-22 08:37 UTC, al3xa23 commented
arm64 is inclued. But for some reason, the tag PI5 only works in capital letters.

2024-10-31 10:10 UTC, stv0g commented
@al3xa23 The Runner configuration in GitLab was missing the correct (lowercase) tag. I have fixed this:

2024-10-31 10:12 UTC, stv0g commented on .gitlab-ci.yml
> +        TAG: PI5
```suggestion
        TAG: pi5
```

2024-10-31 10:47 UTC, stv0g approved these changes

2024-10-31 10:58 UTC, merged