Add a device tree reader for ip-devices
VILLASframework/node pull request #838
Opened 2024-11-20 23:53 UTC by IgnoreWarnings

Create ip-device objects  from an os devices directory.

2024-11-21 07:49 UTC, n-eiling requested changes

2024-11-21 07:49 UTC, n-eiling commented on common/include/villas/kernel/devices/ip_device_reader.hpp
> +class IpDeviceReader {
Why do you create a class for this? Wouldn't this make more sense as a function?

2024-11-21 07:49 UTC, n-eiling commented on common/include/villas/kernel/devices/ip_device_reader.hpp
> +  read(std::filesystem::path devices_directory) const {
Are you sure you are using the correct clang-format config? This looks not like other code in VILLASnode.

2024-12-05 13:27 UTC, n-eiling approved these changes

2024-12-05 13:27 UTC, n-eiling commented
@stv0g can you add your review please?

2025-01-07 15:02 UTC, n-eiling commented
@stv0g ping

2025-01-24 10:55 UTC, n-eiling commented
@stv0g ping

2025-01-28 16:49 UTC, stv0g approved these changes

2025-01-28 16:49 UTC, merged